server:
  port: 9001
eureka:
  client:
    serviceUrl: # eureka server的路径
      defaultZone: http://localhost:9200/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}:@project.version@
spring:
  application:
    name: cloud-gateway
  #网关的配置
  cloud:
    gateway:
      routes: #配置路由
        - id: instance-cloud-service-rpc
          uri: lb://cloud-service-rpc
          predicates: #当断言成功后，交给某一个微服务处理时使用的是转发
            - Path=/rpc/**
        - id: instance-cloud-service-demo
          uri: lb://cloud-service-demo
          predicates:
            - Path=/demo/**